export const PILLARS = [
  {
    key: 'product_adoption',
    label: 'Product Adoption',
    shortLabel: 'PA',
    weight: 10,
    isContinuous: true,
    description: 'Platform usage across database health, engagement efforts, and recency indicators (0–50 score)',
  },
  {
    key: 'alp',
    label: 'Alumni Leadership Program',
    shortLabel: 'ALP',
    weight: 10,
    isContinuous: false,
    description: 'In-person ALP batch attendance (Hyderabad, Pune, Bengaluru, Delhi, Mumbai)',
  },
  {
    key: 'ascend_elite',
    label: 'Ascend Elite',
    shortLabel: 'Ascend',
    weight: 10,
    isContinuous: false,
    description: 'Ascend Elite executive hiring module activated on customer platform',
  },
  {
    key: 'hoopstr_live',
    label: 'Hoopstr Live',
    shortLabel: 'Live',
    weight: 10,
    isContinuous: false,
    description: 'Hoopstr Live product is activated for the customer',
  },
  {
    key: 'hoopstr_affinity',
    label: 'Hoopstr Affinity',
    shortLabel: 'Affinity',
    weight: 10,
    isContinuous: false,
    description: 'Hoopstr Affinity product is activated for the customer',
  },
  {
    key: 'group_insurance',
    label: 'Group Insurance',
    shortLabel: 'Insurance',
    weight: 10,
    isContinuous: false,
    description: 'Group Insurance activated for the alumni network',
  },
  {
    key: 'vanguard',
    label: 'Vanguard',
    shortLabel: 'Vanguard',
    weight: 10,
    isContinuous: false,
    description: 'Enrolled in Outcomes Focused Programs (Vanguard)',
  },
  {
    key: 'magic_ai',
    label: 'Magic AI',
    shortLabel: 'Magic AI',
    weight: 10,
    isContinuous: false,
    description: 'Magic AI feature set is part of the active plan',
  },
  {
    key: 'campus_visit',
    label: 'Campus Visit',
    shortLabel: 'Campus',
    weight: 10,
    isContinuous: false,
    description: 'In-person visit to the customer\'s campus',
  },
  {
    key: 'upsell_demo',
    label: 'Upsell Demo',
    shortLabel: 'Demo',
    weight: 10,
    isContinuous: false,
    description: 'Demonstration of upsell products conducted for the customer',
  },
];

export const PILLAR_MAP = Object.fromEntries(PILLARS.map(p => [p.key, p]));
