import { enrichCustomer } from './scoring';

// Raw input columns only — pa_score/pa_status computed on load.
// signup_date drives age calculation for ideal events/news.
// Reference date: 13 May 2026
const RAW = [
  {
    site_id: '1001', code: 'IIT-B', customer: 'IIT Bombay', city: 'Mumbai', state: 'Maharashtra',
    signup_date: '13 May 2018',
    registered_db: '920', unregistered_db: '80', pend_app: '3',
    events: '72', last_event_date: '28 Apr 2026', news: '156', last_news_date: '05 May 2026',
    chapters: '4', sigs: '6', last_login_date: '11 May 2026', last_mailer_date: '21 Apr 2026',
    alp: 'MUM', ascend_elite: 'Yes', group_insurance: 'Yes', hoopstr_live: 'Yes',
    hoopstr_affinity: 'Yes', vanguard: 'Yes', magic_ai: 'Yes',
    campus_visited: 'Yes', campus_visit_date: '10 Jan 2026', last_demo_date: '05 Apr 2026',
  },
  {
    site_id: '1002', code: 'XLRI', customer: 'XLRI Jamshedpur', city: 'Jamshedpur', state: 'Jharkhand',
    signup_date: '13 May 2020',
    registered_db: '850', unregistered_db: '150', pend_app: '7',
    events: '45', last_event_date: '08 Apr 2026', news: '98', last_news_date: '23 Apr 2026',
    chapters: '2', sigs: '3', last_login_date: '08 May 2026', last_mailer_date: '15 Apr 2026',
    alp: 'HYD', ascend_elite: 'Yes', group_insurance: 'No', hoopstr_live: 'Yes',
    hoopstr_affinity: 'Yes', vanguard: 'Yes', magic_ai: 'Yes',
    campus_visited: 'Yes', campus_visit_date: '18 Feb 2026', last_demo_date: '12 Apr 2026',
  },
  {
    site_id: '1003', code: 'IIMB', customer: 'IIM Bangalore', city: 'Bengaluru', state: 'Karnataka',
    signup_date: '13 May 2016',
    registered_db: '950', unregistered_db: '50', pend_app: '2',
    events: '88', last_event_date: '03 May 2026', news: '200', last_news_date: '08 May 2026',
    chapters: '5', sigs: '8', last_login_date: '12 May 2026', last_mailer_date: '25 Apr 2026',
    alp: 'BLR', ascend_elite: 'Yes', group_insurance: 'Yes', hoopstr_live: 'No',
    hoopstr_affinity: 'Yes', vanguard: 'Yes', magic_ai: 'Yes',
    campus_visited: 'Yes', campus_visit_date: '22 Mar 2026', last_demo_date: '30 Apr 2026',
  },
  {
    site_id: '1004', code: 'SPJIMR', customer: 'SPJIMR Mumbai', city: 'Mumbai', state: 'Maharashtra',
    signup_date: '13 May 2021',
    registered_db: '544', unregistered_db: '256', pend_app: '5',
    events: '30', last_event_date: '13 Mar 2026', news: '60', last_news_date: '28 Mar 2026',
    chapters: '1', sigs: '2', last_login_date: '25 Apr 2026', last_mailer_date: '18 Mar 2026',
    alp: 'PUN', ascend_elite: 'No', group_insurance: 'No', hoopstr_live: 'Yes',
    hoopstr_affinity: 'No', vanguard: 'No', magic_ai: 'Yes',
    campus_visited: 'Yes', campus_visit_date: '08 Dec 2025', last_demo_date: '15 Mar 2026',
  },
  {
    site_id: '1005', code: 'NMIMS', customer: 'NMIMS University', city: 'Mumbai', state: 'Maharashtra',
    signup_date: '13 May 2022',
    registered_db: '330', unregistered_db: '270', pend_app: '12',
    events: '20', last_event_date: '27 Feb 2026', news: '45', last_news_date: '18 Mar 2026',
    chapters: '0', sigs: '1', last_login_date: '15 Apr 2026', last_mailer_date: '01 Apr 2026',
    alp: 'No', ascend_elite: 'No', group_insurance: 'No', hoopstr_live: 'Yes',
    hoopstr_affinity: 'No', vanguard: 'No', magic_ai: 'No',
    campus_visited: 'Yes', campus_visit_date: '20 Nov 2025', last_demo_date: '10 Feb 2026',
  },
  {
    site_id: '1006', code: 'BITS-P', customer: 'BITS Pilani', city: 'Pilani', state: 'Rajasthan',
    signup_date: '13 May 2019',
    registered_db: '720', unregistered_db: '180', pend_app: '4',
    events: '55', last_event_date: '01 Apr 2026', news: '110', last_news_date: '15 Apr 2026',
    chapters: '3', sigs: '4', last_login_date: '03 May 2026', last_mailer_date: '08 Apr 2026',
    alp: 'DEL', ascend_elite: 'Yes', group_insurance: 'No', hoopstr_live: 'No',
    hoopstr_affinity: 'No', vanguard: 'No', magic_ai: 'Yes',
    campus_visited: 'No', campus_visit_date: '', last_demo_date: '25 Mar 2026',
  },
  {
    site_id: '1007', code: 'TISS', customer: 'TISS Mumbai', city: 'Mumbai', state: 'Maharashtra',
    signup_date: '13 May 2023',
    registered_db: '190', unregistered_db: '310', pend_app: '18',
    events: '10', last_event_date: '03 Feb 2026', news: '20', last_news_date: '12 Feb 2026',
    chapters: '0', sigs: '0', last_login_date: '19 Mar 2026', last_mailer_date: '07 Feb 2026',
    alp: 'No', ascend_elite: 'No', group_insurance: 'No', hoopstr_live: 'No',
    hoopstr_affinity: 'No', vanguard: 'No', magic_ai: 'No',
    campus_visited: 'Yes', campus_visit_date: '15 Sep 2025', last_demo_date: '20 Jan 2026',
  },
  {
    site_id: '1008', code: 'MDI-G', customer: 'MDI Gurgaon', city: 'Gurugram', state: 'Haryana',
    signup_date: '13 May 2023',
    registered_db: '88', unregistered_db: '312', pend_app: '25',
    events: '5', last_event_date: '14 Dec 2025', news: '10', last_news_date: '13 Jan 2026',
    chapters: '0', sigs: '0', last_login_date: '07 Feb 2026', last_mailer_date: '03 Jan 2026',
    alp: 'No', ascend_elite: 'No', group_insurance: 'No', hoopstr_live: 'No',
    hoopstr_affinity: 'No', vanguard: 'No', magic_ai: 'No',
    campus_visited: 'No', campus_visit_date: '', last_demo_date: '05 Nov 2025',
  },
  {
    site_id: '1009', code: 'SPA-D', customer: 'SPA Delhi', city: 'New Delhi', state: 'Delhi',
    signup_date: '13 May 2024',
    registered_db: '27', unregistered_db: '273', pend_app: '35',
    events: '2', last_event_date: '25 Oct 2025', news: '5', last_news_date: '15 Nov 2025',
    chapters: '0', sigs: '0', last_login_date: '13 Jan 2026', last_mailer_date: '13 Nov 2025',
    alp: 'No', ascend_elite: 'No', group_insurance: 'No', hoopstr_live: 'No',
    hoopstr_affinity: 'No', vanguard: 'No', magic_ai: 'No',
    campus_visited: 'No', campus_visit_date: '', last_demo_date: '',
  },
  {
    site_id: '1010', code: 'ISB', customer: 'ISB Hyderabad', city: 'Hyderabad', state: 'Telangana',
    signup_date: '13 May 2017',
    registered_db: '940', unregistered_db: '60', pend_app: '1',
    events: '95', last_event_date: '05 May 2026', news: '180', last_news_date: '10 May 2026',
    chapters: '6', sigs: '9', last_login_date: '12 May 2026', last_mailer_date: '01 May 2026',
    alp: 'HYD', ascend_elite: 'Yes', group_insurance: 'Yes', hoopstr_live: 'Yes',
    hoopstr_affinity: 'Yes', vanguard: 'Yes', magic_ai: 'Yes',
    campus_visited: 'Yes', campus_visit_date: '15 Apr 2026', last_demo_date: '02 May 2026',
  },
  {
    site_id: '1011', code: 'IRMA', customer: 'IRMA Anand', city: 'Anand', state: 'Gujarat',
    signup_date: '13 May 2021',
    registered_db: '372', unregistered_db: '228', pend_app: '8',
    events: '28', last_event_date: '08 Mar 2026', news: '55', last_news_date: '23 Mar 2026',
    chapters: '1', sigs: '1', last_login_date: '21 Apr 2026', last_mailer_date: '25 Mar 2026',
    alp: 'No', ascend_elite: 'No', group_insurance: 'No', hoopstr_live: 'No',
    hoopstr_affinity: 'No', vanguard: 'Yes', magic_ai: 'No',
    campus_visited: 'Yes', campus_visit_date: '28 Feb 2026', last_demo_date: '18 Apr 2026',
  },
  {
    site_id: '1012', code: 'MICA', customer: 'MICA Ahmedabad', city: 'Ahmedabad', state: 'Gujarat',
    signup_date: '13 May 2022',
    registered_db: '225', unregistered_db: '275', pend_app: '20',
    events: '8', last_event_date: '13 Jan 2026', news: '18', last_news_date: '01 Feb 2026',
    chapters: '0', sigs: '0', last_login_date: '05 Mar 2026', last_mailer_date: '18 Jan 2026',
    alp: 'No', ascend_elite: 'No', group_insurance: 'No', hoopstr_live: 'No',
    hoopstr_affinity: 'No', vanguard: 'No', magic_ai: 'No',
    campus_visited: 'No', campus_visit_date: '', last_demo_date: '10 Dec 2025',
  },
];

export const SAMPLE_CUSTOMERS = RAW.map(enrichCustomer);
export const SAMPLE_REPORT_DATE = '13 May 2026';
